org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=128m
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=false
org.gradle.configuration-cache=false
mod_version=0.6.2+1.21.1-neoforge
maven_group=com.sandymandy.pleasurehorizons
archives_base_name=pleasure-horizons
minecraft_version=1.21.1
neo_version=21.1.80
moddev_gradle_version=2.0.80
geckolib_version=5.2.0
sbl_version=1.16.10
cloth_config_version=19.0.147
